name: permission_handler
description: Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
version: 12.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: permission_handler_android
      ios:
        default_package: permission_handler_apple
      web:
        default_package: permission_handler_html
      windows:
        default_package: permission_handler_windows

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  permission_handler_android:
    path: ../permission_handler_android
  permission_handler_apple:
    path: ../permission_handler_apple
  permission_handler_html:
    path: ../permission_handler_html
  permission_handler_windows:
    path: ../permission_handler_windows
  permission_handler_platform_interface:
    path: ../permission_handler_platform_interface

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  plugin_platform_interface: ^2.0.0
